name: application_icon
description: This package provides a widget which shows the application icon of your app.
version: 0.1.0
homepage: https://uekoetter.dev/
repository: https://github.com/ueman/application_icon
issue_tracker: https://github.com/ueman/application_icon/issues

environment:
  sdk: ">=2.8.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' and Android 'package' identifiers should not ordinarily
  # be modified. They are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
      android:
        package: de.ju.application_icon
        pluginClass: ApplicationIconPlugin
      ios:
        pluginClass: ApplicationIconPlugin